Add enable/disable actions

diff --git a/inet b/inet
--- a/inet
+++ b/inet
@@ -34,25 +34,26 @@ usage() {
   echo "  -k, --dry-run     Dry run"
   echo
   echo "ACTIONS:"
-  echo "  curl [-- ARGS]    Check connectivity (generate_204 by default)"
-  echo "  dig [-- ARGS]     Check DNS resolution (google.com by default)"
-  echo "  exec CMD          Execute a command for every WAN interface"
-  echo "  ifup|infdown      Bring interface(s) up or down"
-  echo "  ip                Show IP addresses"
-  echo "  lte [--permanent] Failover to LTE"
-  echo "  ping [-- ARGS]    Connectivity debug (ping)"
-  echo "  public-ip         Determine public IP of every WAN interface"
-  echo "  reset [--force]   Reset wan connection (to $WAN_IPV4/$WAN_IPV6)"
-  echo "  status            Show wan connection status"
-  echo "  speedtest         Perform a librespeed speedtest for every WAN interface"
-  echo "  reboot            Reboot vodafone station, and the OpenWRT router"
-  echo "  svc-restart SVC   Restart init.d services"
-  echo "              all   *ALL* services: all from below"
-  echo "              core  core services: ${CORE_SERVICES[*]}"
-  echo "              dns   DNS services: ${DNS_SERVICES[*]}"
-  echo "              vpn   VPN services: ${VPN_SERVICES[*]}"
-  echo "  upstream-dns      Query upstream DNS server"
-  echo "  vodafone [-y]     Restart Vodafone Station"
+  echo "  curl [-- ARGS]       Check connectivity (generate_204 by default)"
+  echo "  dig [-- ARGS]        Check DNS resolution (google.com by default)"
+  echo "  enable|disable IFACE Soft-en/disable an interface (similar to --permanent)"
+  echo "  exec CMD             Execute a command for every WAN interface"
+  echo "  ifup|ifdown          Bring interface(s) up or down"
+  echo "  ip                   Show IP addresses"
+  echo "  lte [--permanent]    Failover to LTE"
+  echo "  ping [-- ARGS]       Connectivity debug (ping)"
+  echo "  public-ip            Determine public IP of every WAN interface"
+  echo "  reset [--force]      Reset wan connection (to $WAN_IPV4/$WAN_IPV6)"
+  echo "  status               Show wan connection status"
+  echo "  speedtest            Perform a librespeed speedtest for every WAN interface"
+  echo "  reboot               Reboot vodafone station, and the OpenWRT router"
+  echo "  svc-restart SVC      Restart init.d services"
+  echo "              all      *ALL* services: all from below"
+  echo "              core     core services: ${CORE_SERVICES[*]}"
+  echo "              dns      DNS services: ${DNS_SERVICES[*]}"
+  echo "              vpn      VPN services: ${VPN_SERVICES[*]}"
+  echo "  upstream-dns         Query upstream DNS server"
+  echo "  vodafone [-y]        Restart Vodafone Station"
 }
 
 ip() {
@@ -190,7 +191,7 @@ ifdown_multi() {
   ifup_or_down_multi ifdown "$@"
 }
 
-perma_ignore_interfaces() {
+iface_disable() {
   local intf
   for intf in "$@"
   do
@@ -200,7 +201,7 @@ perma_ignore_interfaces() {
   uci commit network
 }
 
-reset_perma_ignore_interfaces() {
+iface_enable() {
   local intf
   for intf in "$@"
   do
@@ -208,6 +209,107 @@ reset_perma_ignore_interfaces() {
     uci delete "network.${intf}.custom_hotplug_no_default_route"
   done
   uci commit network
+}
+
+iface_enable_or_disable_multi() {
+  local action="$1"  # enable/disable
+  case "$action" in
+    enable|disable)
+      # valid action
+      ;;
+    *)
+      echo_error "Invalid action: $action"
+      return 1
+      ;;
+  esac
+
+  local target_interfaces=()
+
+  if [[ -z "$2" ]]
+  then
+    echo_error "No target interface(s) specified."
+    return 2
+  fi
+
+  case "$2" in
+    wan|vodafone)
+      if [[ -n "$IPV4_ONLY" ]]
+      then
+        target_interfaces=("$WAN_IPV4")
+      elif [[ -n "$IPV6_ONLY" ]]
+      then
+        target_interfaces=("$WAN_IPV6")
+      else
+        target_interfaces=("$WAN_IPV4" "$WAN_IPV6")
+      fi
+      ;;
+    wan4)
+      if [[ -n "$IPV6_ONLY" ]]
+      then
+        echo_error "Invalid combination: -6 $2"
+        return 1
+      fi
+      target_interfaces=("$WAN_IPV4")
+      ;;
+    wan6)
+      if [[ -n "$IPV4_ONLY" ]]
+      then
+        echo_error "Invalid combination: -4 $2"
+        return 1
+      fi
+      target_interfaces=("$WAN_IPV6")
+      ;;
+    lte|wwan)
+      if [[ -n "$IPV4_ONLY" ]]
+      then
+        target_interfaces=("$LTE_IPV4")
+      elif [[ -n "$IPV6_ONLY" ]]
+      then
+        target_interfaces=("$LTE_IPV6")
+      else
+        target_interfaces=("$LTE_IPV4" "$LTE_IPV6")
+      fi
+      ;;
+    lte4|wwan4)
+      if [[ -n "$IPV6_ONLY" ]]
+      then
+        echo_error "Invalid combination: -6 $2"
+        return 1
+      fi
+      target_interfaces=("$LTE_IPV4")
+      ;;
+    lte6|wwan6)
+      if [[ -n "$IPV4_ONLY" ]]
+      then
+        echo_error "Invalid combination: -4 $2"
+        return 1
+      fi
+      target_interfaces=("$LTE_IPV6")
+      ;;
+    all)
+      target_interfaces=("${WAN_INTERFACES[@]}")
+      ;;
+    *)
+      echo_error "Unknown target interface(s): $2"
+      return 2
+      ;;
+  esac
+
+  if [[ -z "${target_interfaces[*]}" ]]
+  then
+    echo_warning "No interfaces to run $action against."
+    return 1
+  fi
+
+  "iface_${action}" "${target_interfaces[@]}"
+}
+
+iface_enable_multi() {
+  iface_enable_or_disable_multi enable "$@"
+}
+
+iface_disable_multi() {
+  iface_enable_or_disable_multi disable "$@"
 }
 
 fix-route6() {
@@ -266,19 +368,35 @@ mwan3_is_patched() {
 }
 
 wan_status() {
-  local intf
+  local intf disabled
   for intf in "${WAN_INTERFACES[@]}"
   do
-    ifstatus "$intf" | jq -er --arg intf "$intf" '
-      $intf + ": " + (
-        if .up
-        then
-          "\u001b[32mup"
-        else
-          "\u001b[31mDOWN"
-        end
-      ) + "\u001b[0m"
-    '
+    disabled=$(interface_is_disabled "$intf" && echo true || echo false)
+
+    ifstatus "$intf" | jq -er \
+      --arg intf "$intf" \
+      --argjson disabled "$disabled" \
+      '
+        $intf + ": " + (
+          (
+            if .up
+            then
+              "\u001b[32mup"
+            else
+              "\u001b[31mDOWN"
+            end
+          )
+          + "\u001b[0m" +
+          (
+            if $disabled
+            then
+              " \u001b[31m(disabled!)"
+            else
+              ""
+            end
+          )
+        ) + "\u001b[0m"
+      '
   done
 }
 
@@ -319,6 +437,13 @@ interface_is_up() {
   ifstatus "$1" | jq -er '.up == true' &>/dev/null
 }
 
+interface_is_disabled() {
+  local intf="$1"
+  local val
+  val=$(uci get "network.${intf}.custom_hotplug_no_default_route" 2>/dev/null)
+  [[ "$val" == "1" ]]
+}
+
 wan_reset() {
   if [[ -n "$FORCE" ]]
   then
@@ -334,7 +459,7 @@ wan_reset() {
   # TODO How about doing this unconditionally?
   case "$1" in
     --perm*)
-      reset_perma_ignore_interfaces "$WAN_IPV4" "$WAN_IPV6"
+      iface_enable "$WAN_IPV4" "$WAN_IPV6"
       ;;
   esac
 
@@ -347,7 +472,7 @@ lte_failover() {
 
   case "$1" in
     --perm*)
-      perma_ignore_interfaces "$WAN_IPV4" "$WAN_IPV6"
+      iface_disable "$WAN_IPV4" "$WAN_IPV6"
       ;;
   esac
 
@@ -893,6 +1018,10 @@ main() {
       shift
       wan_dig "$@"
       ;;
+    disable)
+      shift
+      iface_disable_multi "$@"
+      ;;
     devel*|test*)
       shift
       __devel_test "$@"
@@ -900,6 +1029,10 @@ main() {
     dhcp-dns|upstream-dns)
       shift
       wan_query_ustream_dns "$@"
+      ;;
+    enable)
+      shift
+      iface_enable_multi "$@"
       ;;
     exec)
       shift
